//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public string Employee_employeeID { get; set; }
        public int Activity_activityID { get; set; }
        public int favoriteID { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual employee employee { get; set; }
    }
}
