//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoursworked
    {
        public int entryID { get; set; }
        public decimal hours { get; set; }
        public System.DateTime date { get; set; }
        public string comments { get; set; }
        public System.DateTime TimePeriod_periodEndDate { get; set; }
        public string TimePeriod_Employee_employeeID { get; set; }
        public int Activity_activityID { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual timeperiod timeperiod { get; set; }
    }
}
