//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.activities = new HashSet<activity>();
            this.groups = new HashSet<group>();
        }

        [Display(Name = "ID")]
        public int projectID { get; set; }
        [Display(Name = "Name")]
        public string projectName { get; set; }
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> projectStartDate { get; set; }
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> projectEndDate { get; set; }
        [Display(Name = "Description")]
        public string projectDescription { get; set; }
        [Display(Name = "CapCode")]
        public string projectCapitalCode { get; set; }
        [Display(Name = "Abbreviation")]
        public string projectAbbreviation { get; set; }
        [Display(Name = "Active")]
        public short projectActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity> activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> groups { get; set; }
    }
}
